# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  ##management.endpoint.health.group.liveness.include=livenessstate,cacheCheck
  endpoint:
    health:
      probes:
        enabled: true
tracing:
  url: http://localhost:4317
