# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
