version: '3.7'

services:
  jaeger:
    container_name: JaegerTracing
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true