version: '3.8'
services:
  service-registry:
    build: ./services/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - ecommerce-net

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - ecommerce-net

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    networks:
      - ecommerce-net

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    networks:
      - ecommerce-net

  cart-service:
    build: ./services/cart-service
    container_name: cart-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - product-service
    networks:
      - ecommerce-net

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - product-service
    networks:
      - ecommerce-net

  order-cache-service:
    build: ./services/order-cache-service
    container_name: order-cache-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
