# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
spring:
  application:
    name: product-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
