# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 0
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[1000,9999]}

