# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 0
spring:
  application:
    name: cart-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[1000,9999]}
management:
  tracing:
    sampling:
      probability: 1.0
  ##management.endpoint.health.group.liveness.include=livenessstate,cacheCheck
  endpoint:
    health:
      probes:
        enabled: true
tracing:
  url: http://localhost:4317
