# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
spring:
  application:
    name: order-cache-service
server:
  port: 8085
