### GET request without authorization
# @name GetCart
GET http://{{host}}:8080/carts

### GET request with authorization
# @name GetCart
GET http://{{host}}:8080/carts
Authorization: Token

### POST add product to cart
# @name AddProductToCart
POST http://{{host}}:8080/carts
Content-Type: application/json
Authorization: Token

{
  "id": "0ce00091-4e48-483b-9a5e-2c0673c2e43c",
  "name": "MacBook Pro",
  "description": "Apple MacBook Pro 16GB black",
  "price": 1399.99
}
